version: '3.8'

services:
  backend:
    container_name: rag-app
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    networks:
      - rag-network

  frontend:
    container_name: streamlit
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - rag-network

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - rag-network

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama/models
    networks:
      - rag-network

volumes:
  qdrant_storage:
  ollama_models:

networks:
  rag-network:
